{{- $values := .Values }}

{{- range $index, $middlewareData := .Values.middlewares.addPrefix }}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $middlewareData.name }}

spec:
  addPrefix:
    prefix: {{ $middlewareData.prefix }}
{{- end }}
