{{- $values := .Values }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ ternary (printf "%v-compress" $.Release.Name) "compress" $.Values.ingressClass.enabled }}

spec:
  compress: {}
---
# Here, an average of 300 requests per second is allowed.
# In addition, a burst of 200 requests is allowed.
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "basic-ratelimit"

spec:
  rateLimit:
    average: 600
    burst: 400
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "basic-secure-headers"

spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - HEAD
      - PUT
    accessControlMaxAge: 100
    stsSeconds: 63072000
    # stsIncludeSubdomains: false
    # stsPreload: false
    forceSTSHeader: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: same-origin
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      server: ''
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "chain-basic"

spec:
  chain:
    middlewares:
    - name: "basic-ratelimit"
    - name: "basic-secure-headers"
    - name: "compress"
