{{- $values := .Values }}

{{ range $index, $middlewareData := .Values.middlewares.ipWhiteList }}

---
# Declaring the user list
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $middlewareData.name }}

spec:
  ipWhiteList:
    sourceRange:
      {{- range $middlewareData.sourceRange }}
      - {{ . }}
      {{- end }}
    {{- if $middlewareData.ipStrategy }}
    ipStrategy:
      {{- if $middlewareData.ipStrategy.depth }}
      depth: {{ $middlewareData.ipStrategy.depth }}
      {{- end }}
      {{- if $middlewareData.ipStrategy.excludedIPs }}
      excludedIPs:
        {{- range $middlewareData.ipStrategy.excludedIPs }}
        - {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
{{ end }}
