{{- $values := .Values }}

{{ range $index, $middlewareData := .Values.middlewares.rateLimit }}

---
# Declaring the user list
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $middlewareData.name }}

spec:
  rateLimit:
    average: {{ $middlewareData.average }}
    burst: {{ $middlewareData.burst }}
{{ end }}
