{{- $values := .Values }}

{{- range $index, $middlewareData := .Values.middlewares.realIP }}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $middlewareData.name }}

spec:
  plugin:
    traefik-real-ip:
      excludednets:
        {{- range $middlewareData.excludedNetworks }}
        - {{ . | quote }}
        {{- end }}
{{- end }}
