{{- $values := .Values }}

{{ range $index, $middlewareData := .Values.middlewares.redirectScheme }}

---
# Declaring the user list
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $middlewareData.name }}

spec:
  redirectScheme:
    scheme: {{ $middlewareData.scheme }}
    permanent: {{ $middlewareData.permanent }}
{{ end }}
