{{- $values := .Values }}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "tc-opencors-chain"

spec:
  chain:
    middlewares:
    - name: "basic-ratelimit"
    - name: "tc-opencors-headers"
    - name:  "compress"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "tc-closedcors-chain"

spec:
  chain:
    middlewares:
    - name: "basic-ratelimit"
    - name: "tc-closedcors-headers"
    - name: "compress"
