{{- $values := .Values }}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "tc-nextcloud-redirectregex-dav"

spec:
  redirectRegex:
    regex: "https://(.*)/.well-known/(card|cal)dav"
    replacement: "https://${1}/remote.php/dav/"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "tc-nextcloud-chain"

spec:
  chain:
    middlewares:
    - name: "tc-nextcloud-redirectregex-dav"
